#!/bin/bash

# if ! command -v git &> /dev/null
# then
#   brew upgrade git
# else
#   brew install git
#   git config advice.ignoredHook false
# fi

# if ! command -v brew &> /dev/null
# then
#   # Install Homebrew
#   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
# else 
#   echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/ian/.zprofile
#   eval "$(/opt/homebrew/bin/brew shellenv)"
# fi

# Setup Terminal
# brew install --cask iterm2
# rm -r /Users/ian/.oh-my-zsh
# brew install zsh
# sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
# brew install zsh-completions

# brew install zplug

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# brew install ack
# brew install bash-completion
# brew install tree

# # Vim
# brew install vim

# # VSCode
# brew install --cask visual-studio-code

# # Slack
# brew install --cask slack

# # Github CLI
# brew install gh

# # Discord
# brew install --cask discord

# # Node 
# curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# # Python
# brew install pyenv

# # Ruby
# brew install rbenv ruby-build

# # CMake
# brew install cmake

# /bin/bash -c ./install

# # Setup git
# git config --global core.excludesfile ~/.gitignore

# /bin/bash -c ./macos

# source ~/.zshrc

# /bin/bash -c ./post_install_fresh
